filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/icmp.log
    tags: ["icmp", "victima"]
    fields:
      fuente: "victima-icmp"
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: false
