input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIME:hora} IP %{IP:ip_origen} > %{IP:ip_destino}: ICMP %{GREEDYDATA:icmp_tipo}"
    }
  }

  mutate {
    add_field => {
      "tipo_evento" => "ICMP"
      "victima"     => "172.20.0.10"
    }
  }

  ruby {
    code => "event.set('@timestamp', LogStash::Timestamp.now)"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "icmp-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
